name: feature_by_folder
description: This is a package that helps you create a `feature-by-folder` structure for organizing code and resources in a Flutter app.
version: 0.0.5
homepage: https://github.com/sibilrahman/feature_by_folder.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

executables:
  f: f
    # script: feature_by_folder.dart
